### ISSUE TITLE
누적 렙 표시 

### ISSUE THREAD

**Issue by littleKingdom26** [littleKingdom26/acccinfo#16]
누적 랩 표시 - 라피스 

해당 내용은 
자주쿠님이 확인 결과 

보류하기로 결정

**Comment by JAJUKU0064** [comment]
누적랩은 드라이버 아이디 클릭시, 스팀마크 옆에 총 랩수 누적기록이 떳으면 좋겠어요, 그리고 트랙별 랩수,
