### ISSUE TITLE
Driver 클릭 시, 생성되는 UI 개선건

### ISSUE THREAD

**Issue by padagi20** [littleKingdom26/acccinfo#2]
Driver의 타 트랙에서의 기록이 표시되는 UI가 추가되었습니다.
간단게 타 트랙의 정보를 보는건 유용하나, 각 트랙의 수준을 알기엔 힘들 수 있습니다.
생성되는 팝업에서 Gap정보 혹은 해당 기록의 Rank를 표시해 주는 UI를 제안합니다.
구현 전 의견 comment 부탁드립니다.

**Comment by littleKingdom26** [comment]
랭크를 넣기엔 쿼리가 복잡해질꺼같구요 음.. Gap 정보는 어떻게 뽑아올수 있을꺼같아요..

**Comment by padagi20** [comment]
니콜님 콜라버레이터 등록 후 니콜님께 본 이슈 assign 부탁드립니다.
