### ISSUE TITLE
드라이버 평가 시스템 구축건

### ISSUE THREAD

**Issue by padagi20** [littleKingdom26/acccinfo#23]
리틀님 아래와 같이 제가 점수 계산하는 클래스를 만들면, 반영이 가능할지 확인 부탁드립니다.

class AccumulatedSkillEvaluator
{
    void pushData(int eventID, int rank, int participantNo)
    double getScore();
}

**Comment by littleKingdom26** [comment]
@padagi20 가능합니다~

**Comment by padagi20** [comment]
1차 버전 엔진과 테스트 프로그램 드립니다.

import java.util.*;
import java.lang.*;
import java.io.*;


class AccumulatedSkillEvaluator
{
    private double scoreSum = 0;
    private double weightSum = 0;
    private final int eventPeroid = 10;
    
    public void pushData(int eventID, int rank, int participantNo)
    {
        final double weight = eventPeroid-eventID;
        weightSum += weight;
        scoreSum += weight*rank/participantNo;
    }
    
    public double getScore()
    {
        return (scoreSum/weightSum)*100.0;
    }
}

// Please name your class Main
class Main {
	public static void main (String[] args) throws java.lang.Exception {

        AccumulatedSkillEvaluator cass = new AccumulatedSkillEvaluator();
        cass.pushData(0, 4, 30);
        cass.pushData(1, 10, 30);
        cass.pushData(2, 1, 30);
        cass.pushData(3, 1, 30);
        cass.pushData(4, 1, 30);
        cass.pushData(5, 1, 30);
        cass.pushData(6, 1, 30);
        cass.pushData(7, 3, 30);
        cass.pushData(8, 3, 30);
        cass.pushData(9, 3, 30);

		System.out.print( cass.getScore() );
	}
}

**Comment by littleKingdom26** [comment]
개인 프로필 페이지 완료
관리자 페이지 남음
