### ISSUE TITLE
Version 2의 Feature Ideation.

### ISSUE THREAD

**Issue by padagi20** [littleKingdom26/acccinfo#3]
Version 2의 Feature Ideation comment 에 남겨주세요.

**Comment by padagi20** [comment]
퀄리 외에, 경기 전용 DB 및 페이지 추가

**Comment by littleKingdom26** [comment]
건의게시판 생성(회원제는 고민좀...)

**Comment by littleKingdom26** [comment]
gap에 노출돼는 초에 앞에 0제외

**Comment by padagi20** [comment]
기록에 대한 보상에 대한 고민이 많았는데요, 현재 12,3위에 자동차 아이콘을 부여하고 있었습니다.
개인적으로 트랙별 챔피언(마스터)를 선정하여, 이름 뒤에 항상 뱃지 같은걸 붙여주면 어떨까 합니다.

**Comment by littleKingdom26** [comment]
공지사항, 경기일정,  자유게시판 생성!

**Comment by littleKingdom26** [comment]
> 기록에 대한 보상에 대한 고민이 많았는데요, 현재 12,3위에 자동차 아이콘을 부여하고 있었습니다.
> 개인적으로 트랙별 챔피언(마스터)를 선정하여, 이름 뒤에 항상 뱃지 같은걸 붙여주면 어떨까 합니다.

완료
